# Generated by Django 5.2.14 on 2026-06-15 02:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                (
                    "value",
                    models.JSONField(help_text="支持字符串、数字、布尔值、对象", verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="配置说明"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫配置",
                "verbose_name_plural": "爬虫配置",
                "db_table": "crawler_configs",
            },
        ),
        migrations.CreateModel(
            name="SeedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL地址")),
                (
                    "school",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="所属高校"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "need_render",
                    models.BooleanField(default=False, verbose_name="需要动态渲染"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("crawling", "爬取中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("blocked", "被禁止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "种子URL",
                "verbose_name_plural": "种子URL",
                "db_table": "seed_urls",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("seed_url", models.URLField(verbose_name="种子URL")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签列表"),
                ),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                ("config", models.JSONField(default=dict, verbose_name="爬虫配置")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teacher", "教师信息"),
                            ("course", "课程信息"),
                            ("news", "新闻公告"),
                            ("research", "科研成果"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="模板分类",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        default="qwen2:7b", max_length=100, verbose_name="AI模型"
                    ),
                ),
                (
                    "ai_api_url",
                    models.URLField(
                        default="http://127.0.0.1:11434", verbose_name="AI服务地址"
                    ),
                ),
                (
                    "ai_api_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="API密钥"
                    ),
                ),
                ("user_prompt", models.TextField(blank=True, verbose_name="用户提取指令")),
                (
                    "ai_prompt",
                    models.TextField(blank=True, verbose_name="AI提示词（旧，保留兼容）"),
                ),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "爬取模板",
                "verbose_name_plural": "爬取模板",
                "db_table": "templates",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码哈希")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True, verbose_name="头像")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="任务ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="任务名称"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("preview", "预览任务"), ("formal", "正式采集")],
                        default="formal",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "generated_rule",
                    models.TextField(blank=True, null=True, verbose_name="AI生成的采集规则"),
                ),
                ("seed_url", models.URLField(verbose_name="种子URL")),
                ("max_depth", models.IntegerField(default=2, verbose_name="最大深度")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("stopped", "已停止"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_pages", models.IntegerField(default=0, verbose_name="总页面数")),
                ("success_pages", models.IntegerField(default=0, verbose_name="成功页面数")),
                ("failed_pages", models.IntegerField(default=0, verbose_name="失败页面数")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "traceback",
                    models.TextField(blank=True, null=True, verbose_name="错误堆栈"),
                ),
                (
                    "report",
                    models.TextField(blank=True, null=True, verbose_name="爬虫报告"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.template",
                        verbose_name="关联模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
                "db_table": "crawl_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="template",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.user",
                verbose_name="创建者",
            ),
        ),
        migrations.CreateModel(
            name="PageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL地址")),
                (
                    "raw_html",
                    models.TextField(blank=True, null=True, verbose_name="原始HTML"),
                ),
                (
                    "markdown",
                    models.TextField(blank=True, null=True, verbose_name="Markdown内容"),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="内容哈希"
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("raw_converted", "已基础转Markdown"),
                            ("ai_cleaned", "已AI清洗+结构化提取"),
                            ("error", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="结构化提取数据"
                    ),
                ),
                (
                    "error_info",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("preview", "预览任务"), ("formal", "正式采集")],
                        default="formal",
                        max_length=20,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(blank=True, null=True, verbose_name="用户提取指令"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("teacher", "教师"),
                            ("course", "课程"),
                            ("research", "科研"),
                            ("news", "新闻公告"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        null=True,
                        verbose_name="页面类型",
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片列表"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="最后错误"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.crawltask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "网页快照",
                "verbose_name_plural": "网页快照",
                "db_table": "page_snapshots",
                "unique_together": {("url", "task_id")},
            },
        ),
        migrations.CreateModel(
            name="UserTemplateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.template",
                        verbose_name="模板",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户历史模板",
                "verbose_name_plural": "用户历史模板",
                "db_table": "user_template_history",
                "ordering": ["-used_at"],
                "unique_together": {("user", "template")},
            },
        ),
    ]
