# Generated by Django 5.2.14 on 2026-06-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL地址")),
                ("markdown", models.TextField(verbose_name="Markdown内容")),
                ("content_hash", models.CharField(max_length=64, verbose_name="内容哈希")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
            ],
            options={
                "verbose_name": "网页快照",
                "verbose_name_plural": "网页快照",
                "db_table": "page_snapshots",
            },
        ),
        migrations.CreateModel(
            name="SeedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="URL地址")),
                ("school", models.CharField(max_length=100, verbose_name="所属高校")),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                (
                    "need_render",
                    models.BooleanField(default=False, verbose_name="需要动态渲染"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("crawling", "爬取中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "种子URL",
                "verbose_name_plural": "种子URL",
                "db_table": "seed_urls",
            },
        ),
    ]
