# Generated by Django 5.2.14 on 2026-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
