# Generated by Django 5.2.14 on 2026-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                (
                    "value",
                    models.JSONField(help_text="支持字符串、数字、布尔值、对象", verbose_name="配置值"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="配置说明"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫配置",
                "verbose_name_plural": "爬虫配置",
                "db_table": "crawler_configs",
            },
        ),
        migrations.AlterField(
            model_name="seedurl",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("crawling", "爬取中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("blocked", "被禁止"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
