# Generated by Django 5.2.14 on 2026-06-03 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_crawlerconfig_alter_seedurl_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="任务ID",
                    ),
                ),
                ("seed_url", models.URLField(verbose_name="种子URL")),
                ("max_depth", models.IntegerField(default=2, verbose_name="最大深度")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("total_pages", models.IntegerField(default=0, verbose_name="总页面数")),
                ("success_pages", models.IntegerField(default=0, verbose_name="成功页面数")),
                ("failed_pages", models.IntegerField(default=0, verbose_name="失败页面数")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "traceback",
                    models.TextField(blank=True, null=True, verbose_name="错误堆栈"),
                ),
                (
                    "report",
                    models.TextField(blank=True, null=True, verbose_name="爬虫报告"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "爬虫任务",
                "verbose_name_plural": "爬虫任务",
                "db_table": "crawl_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
