# Generated by Django 5.2.14 on 2026-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="crawler_rule",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="爬虫采集规则（XPath/CSS）"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="rule_generated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="规则生成时间"),
        ),
    ]
