# Generated by Django 5.2.14 on 2026-06-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_template_crawler_rule_template_rule_generated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="review_comment",
            field=models.TextField(blank=True, null=True, verbose_name="审核意见"),
        ),
        migrations.AddField(
            model_name="template",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="template",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_templates",
                to="api.user",
                verbose_name="审核人",
            ),
        ),
    ]
