# Generated by Django 5.2.14 on 2026-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_crawltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesnapshot",
            name="images",
            field=models.JSONField(blank=True, default=list, verbose_name="图片列表"),
        ),
    ]
