# Generated by Django 5.2.14 on 2026-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_template_review_comment_template_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
    ]
