# Generated by Django 5.2.14 on 2026-06-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_pagesnapshot_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                ("seed_url", models.URLField(verbose_name="种子URL")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签列表"),
                ),
                ("ai_prompt", models.TextField(blank=True, verbose_name="AI提示词")),
                ("description", models.TextField(blank=True, verbose_name="模板描述")),
                ("config", models.JSONField(default=dict, verbose_name="爬虫配置")),
                ("usage_count", models.IntegerField(default=0, verbose_name="使用次数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "爬取模板",
                "verbose_name_plural": "爬取模板",
                "db_table": "templates",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="extracted_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="提取数据"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="last_error",
            field=models.TextField(blank=True, null=True, verbose_name="最后错误"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="page_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "教师"),
                    ("course", "课程"),
                    ("research", "科研"),
                    ("unknown", "未知"),
                ],
                max_length=20,
                null=True,
                verbose_name="页面类型",
            ),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="process_error",
            field=models.TextField(blank=True, null=True, verbose_name="处理错误"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="raw_html",
            field=models.TextField(blank=True, null=True, verbose_name="原始HTML"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="重试次数"),
        ),
        migrations.AlterField(
            model_name="crawltask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "运行中"),
                    ("paused", "已暂停"),
                    ("stopped", "已停止"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
