# Generated by Django 5.2.14 on 2026-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_template_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesnapshot",
            name="data_source",
            field=models.CharField(
                blank=True,
                choices=[("crawled", "爬虫采集"), ("imported", "手动导入"), ("api", "API推送")],
                max_length=50,
                null=True,
                verbose_name="数据来源",
            ),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="export_count",
            field=models.IntegerField(default=0, verbose_name="导出次数"),
        ),
        migrations.AddField(
            model_name="pagesnapshot",
            name="exported_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="导出时间"),
        ),
    ]
